### ISSUE TITLE
Condition in replaceChain is always true

### ISSUE THREAD

**Issue by ghost** [mycoralhealth/blockchain-tutorial#10]
* Line 89 `newBlockchain := append(Blockchain, newBlock)` appending new block to blockchain
* Line 138 `if len(newBlocks) > len(Blockchain) {` checking if size of new chain is bigger.

`len(newBlocks)` is always equals to `len(Blockchain) + 1`.

**Comment by nosequeldeebee** [comment]
yeah, this is double checking. Happy to consider alternatives, even removing the `if` condition in `replaceChain`

**Comment by ghost** [comment]
You can remove whole `replaceChain` method, it makes no sense here :) We need to receive whole/part blockchain from other node only if that node sends to us new block, this block is seems to valid, but newBlock.Index > ourLastBlock.Index + 1, for example.

Anyway, without PoW or PoS realisation, network can't come to consensus and choose correct chain to replace, because can't validate chain that received from third-party nodes.

**Comment by nosequeldeebee** [comment]
yes, PoW tutorial is coming next so we'll need a new `replaceChain` function

in the meantime, please send a PR to remove the function if you have time. Otherwise, I'll get to it soon
