### ISSUE TITLE
Medium post converts three dots to single-character ellipsis symbol breaking command

### ISSUE THREAD

**Issue by grempe** [mycoralhealth/blockchain-tutorial#13]
In the Medium post:

https://medium.com/coinmonks/code-a-simple-p2p-blockchain-in-go-46662601f417

The command that should be:

```
go get -d github.com/libp2p/go-libp2p/...
```

Is being converted to:

```
go get -d github.com/libp2p/go-libp2p/…
```

Note, they look the same but the ellipsis is being "helpfully" converted to a single character ellipsis symbol which doesn't work.

**Comment by nosequeldeebee** [comment]
good catch. it's been edited in the post: https://medium.com/coinmonks/code-a-simple-p2p-blockchain-in-go-46662601f417
