### ISSUE TITLE
windows line ending bug

### ISSUE THREAD

**Issue by exeex** [mycoralhealth/blockchain-tutorial#23]
as title:
when I input 70.
it shows a 70\r cause by \r\n line ending in windows.

```
2018/11/08 15:42:57 listening for connections
2018/11/08 15:44:18 Got a new stream!
> 70
2018/11/08 15:47:32 strconv.Atoi: parsing "**70\r**": invalid syntax

```

**Comment by nosequeldeebee** [comment]
it's because windows is adding an automatic carriage return `\r`. Strip that out by trimming the space in your Go code. Add this line:
`sendData = strings.Replace(sendData, "\r", "", -1)` under line 172 and run again

**Comment by ArshadAQ** [comment]
@nosequeldeebee 
Actually I knew of this solution. But was wondering, why in my PC in VSCODE, even though End of line sequence is set to "CRLF", I do not get this error. Any idea why?
