### ISSUE TITLE
Update environment variable to reflect correct value as per Blog

### ISSUE THREAD

**Issue by apooniajjn** [mycoralhealth/blockchain-tutorial#28]
Currently blog part2: Networking says that user should define environment variable as ADDR but in code you are using PORT variable. 

![image](https://user-images.githubusercontent.com/23248841/75633667-caf09d80-5bbb-11ea-8fda-21f620a8ac31.png)

https://github.com/nosequeldeebee/blockchain-tutorial/blob/master/networking/main.go#L50

**Comment by nosequeldeebee** [comment]
Thanks. Will update the blog.
