### ISSUE TITLE
Several Issues running code through visual studio 

### ISSUE THREAD

**Issue by joedakwa** [mycoralhealth/blockchain-tutorial#31]
Hi,

I just tried to run the whole Blockchain code in Visual Studio, and I have had a host of issues.

It would be good if someone could help me understand holistically what is going wrong?

i.e you cannot import "internal/cpu"

This in turn has created problems throughout the code.

**Comment by nosequeldeebee** [comment]
this sounds like an issue with the installation of your Go toolchain and is not specific to this repo. Closing this issue. This might help you get started in debugging: https://stackoverflow.com/questions/46377604/cannot-find-package-internal-cpu-error-in-go
