### ISSUE TITLE
another problem in windows10 terminal

### ISSUE THREAD

**Issue by xuanyuan33521** [mycoralhealth/blockchain-tutorial#36]
when print "70",in windows terminal ,you well see"strconv.Atoi:"70/r" invalid sy
the renson is windows system "Enter" key is"/r" in end.
so change you code in 179 line like this:
sendData = strings.Replace(sendData, "\r", "", -1)

**Comment by nosequeldeebee** [comment]
feel free to submit a PR if you wish. This is a duplicate of #23
