### ISSUE TITLE
may generate blocks with same Index？

### ISSUE THREAD

**Issue by wangzz719** [mycoralhealth/blockchain-tutorial#4]
`newBlock, err := genearteBlock(BlockChain[len(BlockChain)-1], bpm)`
while in high concurrency,  blocks with same Index may be generated?
for example, here is the result in my test

> {
    "Index": 422,
    "TimeStamp": "2018-01-30 13:58:54.183422 +0800 CST m=+753.675702708",
    "BPM": 354,
    "Hash": "224afd49a6cc91b53981401212c9ef77065d10622c65799468c2f7d13a8ba98d",
    "PrevHash": "780bebe0c96726d58d7ade6a64f1f6ae79354e069d63f842c7bd759b843360ed"
  },
  {
    "Index": 423,
    "TimeStamp": "2018-01-30 13:58:54.31362 +0800 CST m=+753.805901260",
    "BPM": 355,
    "Hash": "928ddf91e2095e7e5f892f91fd4f7f77d291c2bfac4e402f1ed6c05e50e7c4ee",
    "PrevHash": "224afd49a6cc91b53981401212c9ef77065d10622c65799468c2f7d13a8ba98d"
  },
  {
    "Index": 423,
    "TimeStamp": "2018-01-30 13:58:54.31362 +0800 CST m=+753.805901306",
    "BPM": 71,
    "Hash": "57aa47f8997bf9197a3e77beae0b79476f9f64b3d8e1d59398c8322941bc1b35",
    "PrevHash": "224afd49a6cc91b53981401212c9ef77065d10622c65799468c2f7d13a8ba98d"
  }

**Comment by artemnl** [comment]
Here should be some mutex to lock index during block generation.

**Comment by nosequeldeebee** [comment]
yes, or cleanly use channels to ensure atomicity
