### ISSUE TITLE
maximum capacity

### ISSUE THREAD

**Issue by atom2ueki** [mycoralhealth/blockchain-tutorial#9]
is there a way to set a maximum capacity on the number of blockchains, when the first block generated ? so that if anyone change that value, hash value will not match

**Comment by nosequeldeebee** [comment]
what do you mean? there is only one blockchain, which is a slice of `block`

do you mean a maximum capacity on the number of blocks? if so, you wouldn't want to do that - there shouldn't be a max number of blocks

also, the hashes are checked anyways `hash` and `prevHash`

I don't think I quite understand your question

**Comment by nosequeldeebee** [comment]
closing this until more info provided
